[general]
connection = "Host=127.0.0.1;Username=api;Password=admin;Database=manager"
output = "Database/DatabaseTypes.fs"
namespace = "Manager.Server.DatabaseTypes"
cli_mutable = true
[sqlhydra_query_integration]
provider_db_type_attributes = true
table_declarations = true
[readers]
reader_type = "Npgsql.NpgsqlDataReader"
[filters]
include = ["recepies/*"]
exclude = ["public/*"]
