// This code was generated by `SqlHydra.Npgsql` -- v2.4.0.
namespace Manager.Server.DatabaseTypes

open SqlHydra
open SqlHydra.Query.Table

[<AutoOpen>]
module ColumnReaders =
    type Column(reader: System.Data.IDataReader, getOrdinal: string -> int, column) =
            member __.Name = column
            member __.IsNull() = getOrdinal column |> reader.IsDBNull
            override __.ToString() = __.Name

    type RequiredColumn<'T, 'Reader when 'Reader :> System.Data.IDataReader>(reader: 'Reader, getOrdinal, getter: int -> 'T, column) =
            inherit Column(reader, getOrdinal, column)
            member __.Read(?alias) = alias |> Option.defaultValue __.Name |> getOrdinal |> getter

    type OptionColumn<'T, 'Reader when 'Reader :> System.Data.IDataReader>(reader: 'Reader, getOrdinal, getter: int -> 'T, column) =
            inherit Column(reader, getOrdinal, column)
            member __.Read(?alias) = 
                match alias |> Option.defaultValue __.Name |> getOrdinal with
                | o when reader.IsDBNull o -> None
                | o -> Some (getter o)

    type NullableObjectColumn<'T, 'Reader when 'Reader :> System.Data.IDataReader>(reader: 'Reader, getOrdinal, getter: int -> 'T, column) =
            inherit Column(reader, getOrdinal, column)
            member __.Read(?alias) = 
                match alias |> Option.defaultValue __.Name |> getOrdinal with
                | o when reader.IsDBNull o -> null
                | o -> (getter o) |> unbox

    type NullableValueColumn<'T, 'Reader when 'T : struct and 'T : (new : unit -> 'T) and 'T :> System.ValueType and 'Reader :> System.Data.IDataReader>(reader: 'Reader, getOrdinal, getter: int -> 'T, column) =
            inherit Column(reader, getOrdinal, column)
            member __.Read(?alias) = 
                match alias |> Option.defaultValue __.Name |> getOrdinal with
                | o when reader.IsDBNull o -> System.Nullable<'T>()
                | o -> System.Nullable<'T> (getter o)

[<AutoOpen>]
module private DataReaderExtensions =
    type System.Data.IDataReader with
        member reader.GetDateOnly(ordinal: int) = 
            reader.GetDateTime(ordinal) |> System.DateOnly.FromDateTime
    
    type System.Data.Common.DbDataReader with
        member reader.GetTimeOnly(ordinal: int) = 
            reader.GetFieldValue(ordinal) |> System.TimeOnly.FromTimeSpan
        

module recepies =
    [<CLIMutable>]
    type ingredient =
        { [<ProviderDbType("Uuid")>]
          ingredient_id: System.Guid
          [<ProviderDbType("Varchar")>]
          name: string }

    let ingredient = table<ingredient>

    [<CLIMutable>]
    type recepie =
        { [<ProviderDbType("Uuid")>]
          recepie_id: System.Guid
          [<ProviderDbType("Varchar")>]
          name: string }

    let recepie = table<recepie>

    [<CLIMutable>]
    type recepie_ingredient =
        { [<ProviderDbType("Uuid")>]
          recepie_id: System.Guid
          [<ProviderDbType("Uuid")>]
          ingredient_id: System.Guid
          [<ProviderDbType("Numeric")>]
          amount: decimal
          [<ProviderDbType("Varchar")>]
          unit: string }

    let recepie_ingredient = table<recepie_ingredient>

    module Readers =
        type ingredientReader(reader: Npgsql.NpgsqlDataReader, getOrdinal) =
            member __.ingredient_id = RequiredColumn(reader, getOrdinal, reader.GetGuid, "ingredient_id")
            member __.name = RequiredColumn(reader, getOrdinal, reader.GetString, "name")

            member __.Read() =
                { ingredient_id = __.ingredient_id.Read()
                  name = __.name.Read() }
                : ingredient

            member __.ReadIfNotNull() =
                if __.ingredient_id.IsNull() then None else Some(__.Read())

        type recepieReader(reader: Npgsql.NpgsqlDataReader, getOrdinal) =
            member __.recepie_id = RequiredColumn(reader, getOrdinal, reader.GetGuid, "recepie_id")
            member __.name = RequiredColumn(reader, getOrdinal, reader.GetString, "name")

            member __.Read() =
                { recepie_id = __.recepie_id.Read()
                  name = __.name.Read() }
                : recepie

            member __.ReadIfNotNull() =
                if __.recepie_id.IsNull() then None else Some(__.Read())

        type recepie_ingredientReader(reader: Npgsql.NpgsqlDataReader, getOrdinal) =
            member __.recepie_id = RequiredColumn(reader, getOrdinal, reader.GetGuid, "recepie_id")
            member __.ingredient_id = RequiredColumn(reader, getOrdinal, reader.GetGuid, "ingredient_id")
            member __.amount = RequiredColumn(reader, getOrdinal, reader.GetDecimal, "amount")
            member __.unit = RequiredColumn(reader, getOrdinal, reader.GetString, "unit")

            member __.Read() =
                { recepie_id = __.recepie_id.Read()
                  ingredient_id = __.ingredient_id.Read()
                  amount = __.amount.Read()
                  unit = __.unit.Read() }
                : recepie_ingredient

            member __.ReadIfNotNull() =
                if __.recepie_id.IsNull() then None else Some(__.Read())

type HydraReader(reader: Npgsql.NpgsqlDataReader) =
    let mutable accFieldCount = 0
    let buildGetOrdinal fieldCount =
        let dictionary = 
            [0..reader.FieldCount-1] 
            |> List.map (fun i -> reader.GetName(i), i)
            |> List.sortBy snd
            |> List.skip accFieldCount
            |> List.take fieldCount
            |> dict
        accFieldCount <- accFieldCount + fieldCount
        fun col -> dictionary.Item col
        
    let lazyrecepiesingredient = lazy (recepies.Readers.ingredientReader(reader, buildGetOrdinal 2))
    let lazyrecepiesrecepie = lazy (recepies.Readers.recepieReader(reader, buildGetOrdinal 2))
    let lazyrecepiesrecepie_ingredient = lazy (recepies.Readers.recepie_ingredientReader(reader, buildGetOrdinal 4))
    member __.``recepies.ingredient`` = lazyrecepiesingredient.Value
    member __.``recepies.recepie`` = lazyrecepiesrecepie.Value
    member __.``recepies.recepie_ingredient`` = lazyrecepiesrecepie_ingredient.Value
    member private __.AccFieldCount with get () = accFieldCount and set (value) = accFieldCount <- value

    member private __.GetReaderByName(entity: string, isOption: bool) =
        match entity, isOption with
        | "recepies.ingredient", false -> __.``recepies.ingredient``.Read >> box
        | "recepies.ingredient", true -> __.``recepies.ingredient``.ReadIfNotNull >> box
        | "recepies.recepie", false -> __.``recepies.recepie``.Read >> box
        | "recepies.recepie", true -> __.``recepies.recepie``.ReadIfNotNull >> box
        | "recepies.recepie_ingredient", false -> __.``recepies.recepie_ingredient``.Read >> box
        | "recepies.recepie_ingredient", true -> __.``recepies.recepie_ingredient``.ReadIfNotNull >> box
        | _ -> failwith $"Could not read type '{entity}' because no generated reader exists."

    static member private GetPrimitiveReader(t: System.Type, reader: Npgsql.NpgsqlDataReader, isOpt: bool, isNullable: bool) =
        let wrapValue get (ord: int) = 
            if isOpt then (if reader.IsDBNull ord then None else get ord |> Some) |> box 
            elif isNullable then (if reader.IsDBNull ord then System.Nullable() else get ord |> System.Nullable) |> box
            else get ord |> box

        let wrapRef get (ord: int) = 
            if isOpt then (if reader.IsDBNull ord then None else get ord |> Some) |> box 
            else get ord |> box
        
        if t = typedefof<bool> then Some(wrapValue reader.GetBoolean)
        elif t = typedefof<bool[]> then Some(wrapRef reader.GetFieldValue<bool[]>)
        elif t = typedefof<int16> then Some(wrapValue reader.GetInt16)
        elif t = typedefof<int16[]> then Some(wrapRef reader.GetFieldValue<int16[]>)
        elif t = typedefof<int> then Some(wrapValue reader.GetInt32)
        elif t = typedefof<int[]> then Some(wrapRef reader.GetFieldValue<int[]>)
        elif t = typedefof<int64> then Some(wrapValue reader.GetInt64)
        elif t = typedefof<int64[]> then Some(wrapRef reader.GetFieldValue<int64[]>)
        elif t = typedefof<double> then Some(wrapValue reader.GetDouble)
        elif t = typedefof<double[]> then Some(wrapRef reader.GetFieldValue<double[]>)
        elif t = typedefof<decimal> then Some(wrapValue reader.GetDecimal)
        elif t = typedefof<decimal[]> then Some(wrapRef reader.GetFieldValue<decimal[]>)
        elif t = typedefof<string> then Some(wrapRef reader.GetString)
        elif t = typedefof<string[]> then Some(wrapRef reader.GetFieldValue<string[]>)
        elif t = typedefof<System.Guid> then Some(wrapValue reader.GetGuid)
        elif t = typedefof<System.Guid[]> then Some(wrapRef reader.GetFieldValue<System.Guid[]>)
        elif t = typedefof<System.TimeSpan> then Some(wrapRef reader.GetTimeSpan)
        elif t = typedefof<System.TimeSpan[]> then Some(wrapRef reader.GetFieldValue<System.TimeSpan[]>)
        elif t = typedefof<System.DateOnly> then Some(wrapValue reader.GetDateOnly)
        elif t = typedefof<System.DateOnly[]> then Some(wrapRef reader.GetFieldValue<System.DateOnly[]>)
        elif t = typedefof<System.TimeOnly> then Some(wrapValue reader.GetTimeOnly)
        elif t = typedefof<System.TimeOnly[]> then Some(wrapRef reader.GetFieldValue<System.TimeOnly[]>)
        elif t = typedefof<System.DateTime> then Some(wrapValue reader.GetDateTime)
        elif t = typedefof<System.DateTime[]> then Some(wrapRef reader.GetFieldValue<System.DateTime[]>)
        elif t = typedefof<System.DateTimeOffset> then Some(wrapValue reader.GetDateTime)
        elif t = typedefof<System.DateTimeOffset[]> then Some(wrapRef reader.GetFieldValue<System.DateTimeOffset[]>)
        elif t = typedefof<byte[]> then Some(wrapRef reader.GetFieldValue<byte[]>)
        elif t = typedefof<char> then Some(wrapRef reader.GetChar)
        elif t = typedefof<char[]> then Some(wrapRef reader.GetFieldValue<char[]>)
        elif t = typedefof<float> then Some(wrapRef reader.GetFloat)
        elif t = typedefof<float[]> then Some(wrapRef reader.GetFieldValue<float[]>)
        else None

    static member Read(reader: Npgsql.NpgsqlDataReader) = 
        let hydra = HydraReader(reader)
                    
        let getOrdinalAndIncrement() = 
            let ordinal = hydra.AccFieldCount
            hydra.AccFieldCount <- hydra.AccFieldCount + 1
            ordinal
            
        let buildEntityReadFn (t: System.Type) = 
            let t, isOpt, isNullable = 
                if t.IsGenericType && t.GetGenericTypeDefinition() = typedefof<Option<_>> then t.GenericTypeArguments[0], true, false
                elif t.IsGenericType && t.GetGenericTypeDefinition() = typedefof<System.Nullable<_>> then t.GenericTypeArguments[0], false, true
                else t, false, false
            
            match HydraReader.GetPrimitiveReader(t, reader, isOpt, isNullable) with
            | Some primitiveReader -> 
                let ord = getOrdinalAndIncrement()
                fun () -> primitiveReader ord
            | None ->
                let nameParts = t.FullName.Split([| '.'; '+' |])
                let schemaAndType = nameParts |> Array.skip (nameParts.Length - 2) |> fun parts -> System.String.Join(".", parts)
                hydra.GetReaderByName(schemaAndType, isOpt)
            
        // Return a fn that will hydrate 'T (which may be a tuple)
        // This fn will be called once per each record returned by the data reader.
        let t = typeof<'T>
        if FSharp.Reflection.FSharpType.IsTuple(t) then
            let readEntityFns = FSharp.Reflection.FSharpType.GetTupleElements(t) |> Array.map buildEntityReadFn
            fun () ->
                let entities = readEntityFns |> Array.map (fun read -> read())
                Microsoft.FSharp.Reflection.FSharpValue.MakeTuple(entities, t) :?> 'T
        else
            let readEntityFn = t |> buildEntityReadFn
            fun () -> 
                readEntityFn() :?> 'T
        
